server:
  port: 11000

spring:
  application:
    name: provider-server


eureka:
  client:
    service-url:
      #需要注册给Eureka Server的地址，也就是将自己注册给哪一个Eureka Server
      defaultZone: http://localhost:13000/eureka,http://localhost:13001/eureka